Traceback (most recent call last):
  File "/Users/thomasmonks/opt/anaconda3/envs/hds_python/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/thomasmonks/opt/anaconda3/envs/hds_python/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/thomasmonks/opt/anaconda3/envs/hds_python/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/thomasmonks/opt/anaconda3/envs/hds_python/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/thomasmonks/opt/anaconda3/envs/hds_python/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/thomasmonks/opt/anaconda3/envs/hds_python/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/thomasmonks/opt/anaconda3/envs/hds_python/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/thomasmonks/opt/anaconda3/envs/hds_python/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def guessed_correctly(guess, correct_answer):
    '''
    Returns True or False to indicate if user has guessed correctly.
    
    Keyword arguments:
    guess -- user's guess
    correct_answer -- the answer that needs to be guessed!
    '''
    return guess == correct_answer
    

def play_game(correct_answer):
    '''
    A game to guess a integer number (between 1 and 10).
    Re-prompts user for guess until correct one is supplied.
    
    Keyword arguments:
    correct_answer -- specified by user
    '''
    
    guess = -1
    
    while not guessed_correctly(guess, correct_answer):
        guess = int(input("Please guess a whole number between 1 and 10: >>"))
    
    print("Well done you guessed correctly!")


#a test: this returns false because the user guessed incorrectly
result = guessed_correctly(guess=5, correct_answer=10) 
print(result)

#a test: this returns true because the user guessed correctly
result2 = guessed_correctly(guess=10, correct_answer=10) 
print(result2)

#rather than repeatedly calling guessed_correctly we have created a loop.
#while guessed_correctly returns false 
#we continue to re-prompt the user for another guess.
play_game(10)
        
        
    
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
[0;32m<ipython-input-7-44cc6a2fac68>[0m in [0;36m<module>[0;34m[0m
[1;32m     38[0m [0;31m#while guessed_correctly returns false[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     39[0m [0;31m#we continue to re-prompt the user for another guess.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 40[0;31m [0mplay_game[0m[0;34m([0m[0;36m10[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     41[0m [0;34m[0m[0m
[1;32m     42[0m [0;34m[0m[0m

[0;32m<ipython-input-7-44cc6a2fac68>[0m in [0;36mplay_game[0;34m(correct_answer)[0m
[1;32m     22[0m [0;34m[0m[0m
[1;32m     23[0m     [0;32mwhile[0m [0;32mnot[0m [0mguessed_correctly[0m[0;34m([0m[0mguess[0m[0;34m,[0m [0mcorrect_answer[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 24[0;31m         [0mguess[0m [0;34m=[0m [0mint[0m[0;34m([0m[0minput[0m[0;34m([0m[0;34m"Please guess a whole number between 1 and 10: >>"[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     25[0m [0;34m[0m[0m
[1;32m     26[0m     [0mprint[0m[0;34m([0m[0;34m"Well done you guessed correctly!"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/hds_python/lib/python3.8/site-packages/ipykernel/kernelbase.py[0m in [0;36mraw_input[0;34m(self, prompt)[0m
[1;32m    843[0m         """
[1;32m    844[0m         [0;32mif[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0m_allow_stdin[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 845[0;31m             raise StdinNotImplementedError(
[0m[1;32m    846[0m                 [0;34m"raw_input was called, but this frontend does not support input requests."[0m[0;34m[0m[0;34m[0m[0m
[1;32m    847[0m             )

[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

